#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# YML Author: Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
# Origin:     https://github.com/l3uddz/plexautoscan
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS ######################################################################
    - name: "Set Known Facts"
      set_fact:
        pgrole: "pgscan"
        extport: "0"

    - name: Token Recall
      shell: "cat /pg/var/plex.token"
      register: token

    - name: Install pip requirements
      pip:
        requirements: /opt/plexguide/menu/pgscan/requirements.txt
        executable: pip2

    - name: "Including cron job"
      include_tasks: "/opt/coreapps/apps/_core.yml"

    - name: Create Basic Directories
      file: "path={{item}} state=directory mode=0775 owner=1000 group=1000"
      with_items:
        - "/pg/data/pgscan/"

    - name: Transfer Files
      copy:
        src: /opt/plexguide/menu/pgscan
        dest: /pg/data
        owner: "1000"
        group: "1000"
        mode: a+x
        force: yes

    - name: Import default config
      template:
        src: /pg/data/pgscan/config/default.config
        dest: /pg/data/pgscan/config.json
        owner: "1000"
        group: "1000"
        mode: 0775
        force: yes

    - name: Set pgscan.py as executable
      file:
        path: /pg/data/pgscan/scan.py
        owner: '1000'
        group: '1000'
        mode: a+x

    - name: "Create /usr/local/bin symlink"
      file:
        src: "/pg/data/pgscan/scan.py"
        dest: "/bin/pgscan"
        state: link

    - name: Check Service's Existance
      stat:
        path: "/etc/systemd/systemd/pgscan.service"
      register: pgp

    - name: Stop service
      service:
        name: pgscan
        state: stopped
      when: pgp.stat.exists

    - name: pgscan Service
      template:
        src: /pg/data/pgscan/system/pgscan.service
        dest: /etc/systemd/system/pgscan.service
        force: yes

    - name: Daemon-Reload
      systemd: state=stopped name=pgscan daemon_reload=yes enabled=no

    - name: Section Updates
      command: "/pg/data/pgscan/scan.py sections"
      tags: plex_autoscan_update_sections

    - name: Mapping Configs
      command: "/pg/data/pgscan/scan.py update_sections"
      tags: plex_autoscan_update_sections

    - name: Start pgscan
      systemd: state=started name=pgscan enabled=yes
